### ISSUE TITLE
[Bug] Pasting this into the search bar crashes HISE

### ISSUE THREAD

**Issue by aaronventure** [christophhart/HISE#408] opened 2023-08-08 11:29 UTC
Paste this 
```
const var shaderNoise = Content.createShader("ChromaticAberration");

pnl_Noise.setPaintRoutine(function(g)
{
g.applyShader(shaderNoise, [0, 0, this.getWidth(), this.getHeight()]);
});
```

Into the search bar and HISE will crash. e77f723b0cf918e78dfb9fbabe74fd0e26ebd112

I discovered this by first creating a new panel and attempting to paste immediately after. After creating the new panel, the focus goes to the search bar and it was pasted there. So I tried simply pasting this into search and yep, it crashes.

**Comment by davidhealey** [comment] 2023-08-08 11:32
Yep confirmed crash here, but the focus didn't automatically change on my system, might be an OS specific thing. I'm assuming you mean the component list search bar?

**Comment by aaronventure** [comment] 2023-08-08 11:35
Yes, the one under "Module Tree". Crashes in the API search bar as well.

Funnily enough, it doesn't crash when pasted into the Project Directory search bar.

**Comment by christoph-hart** [comment] 2023-08-09 07:39
That's because the patch browser used the fuzzy search algorithm and the project browser doesn't. Should be fixed now

**Closed by christoph-hart** 2023-08-09 07:39 UTC
